### ISSUE TITLE
Problem with ImmutableSet

### ISSUE THREAD

**Issue by shanmukhipriya99** [corda/samples-java#9]
`error: package com.google.common.collect does not exist import com.google.common.collect.ImmutableSet;`

I'm getting the above error after inserting the following line:

(https://github.com/corda/samples-java/blob/16ae2325a88a45349f7ce03072fb95885a7270be/Basic/cordapp-example/workflows-java/src/main/java/com/example/flow/ExampleFlow.java#L118)

**Comment by anixon604** [comment]
@shanmukhipriya99 this should be working for you, the dependency for com.google.common.collect is in the project. If you are using IntelliJ can you try going `File -> Invalidate Caches / Restart`

**Comment by shanmukhipriya99** [comment]
I did that but the error remains.

**Comment by anixon604** [comment]
You can try recloning the repository and then following this guide https://training.corda.net/prepare-and-discover/discover-example/ - there is a troubleshooting component on the page if your run into issues with dependency resolution.

**Comment by anixon604** [comment]
I will close this issue for now as it's not applicable to all users. But for further assistance please also check out slack.corda.net, where there are live office hours every Tues/Thurs from 11-12 BST.
